# Generated by Django 4.2.1 on 2023-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
