# Generated by Django 4.2.1 on 2023-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_account_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxConcurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrency', models.IntegerField()),
            ],
        ),
    ]
