# Generated by Django 4.2.1 on 2023-05-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_maxconcurrency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Tasks',
        ),
    ]
