# Generated by Django 4.2.1 on 2023-05-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_rename_city_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maxconcurrency',
            old_name='concurrency',
            new_name='current_concurrency',
        ),
        migrations.AddField(
            model_name='maxconcurrency',
            name='max_concurrency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
