# Generated by Django 4.2.1 on 2023-05-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_tasks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
