# Generated by Django 4.2.1 on 2023-05-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_alter_result_page_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
