# Generated by Django 4.2.1 on 2023-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('run_every_minutes', models.IntegerField()),
                ('next_execution', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
