# Generated by Django 4.2.1 on 2023-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='next_execution',
            field=models.DateTimeField(),
        ),
    ]
