# Generated by Django 4.2.1 on 2023-05-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_alter_tasks_next_execution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='is_running',
        ),
    ]
