# Generated by Django 4.2.1 on 2023-05-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_tasks_cache_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAccountFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_file', models.FileField(upload_to='account_files')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_progress',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(help_text="filename.csv file format.\nThe file must include 2 required fields 'city' and 'state_name'", upload_to='csv_files'),
        ),
    ]
